### ISSUE TITLE
How could i drive a second matrix with mirrored pixels

### ISSUE THREAD

**Issue by Burn-In** [adafruit/FirePendant#1]
For a project of a candle style light i want to have a second LED Matrix on the Backside. It should be showing the mirrored image from the Front Matrix. A simple mirrored wiring doesn't work because of the charlieplexed schematic. A second Driver/Matrix forced with mirrored images from a data_mirrored.h will fail because of 32KiB flash memory limitations. (Or an ATMEGA64)
My thought is to force a second Driver/Matrix with in code mirrored data, like "map x(0, 9, 9, 0 )"...
But unfortunately i understand the code to less that i can do it. Have someone any suggestions?

**Comment by ladyada** [comment]
hiya this isn't a good place to post these sorts of questions - we use github for code issues/bugs/fixes only :)
